name: Release build - JAR

on:
  release:
    types: ["published"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Get version from tag
        id: get-version
        run: echo "version=${GH_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        env:
          GH_REF: ${{ github.ref }}

      - name: Set version in pom.xml
        run: mvn --batch-mode --file pom.xml versions:set '-DnewVersion=${{ steps.get-version.outputs.version }}'

      - name: Build with Maven
        run: mvn --batch-mode --file pom.xml package

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: zatikon-${{ steps.set-version.outputs.version }}
          path: target/zatikon-*.jar

# Well it's cool it can be deployed but I don't need that now
#    - name: Publish package
#      run: mvn --batch-mode deploy
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

# What I need is to create a release on Github and publish latest version on Flathub. TODO: that.
